version = 2
final_space = true
console_title_template = '{{ .Shell }} in {{ .Folder }}'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'session'
    style = 'diamond'
    leading_diamond = ''
    trailing_diamond = ''
    background = '#5f00d7'
    foreground = '#eeeeee'
    template = '󱁇 {{ .UserName }} '

  [[blocks.segments]]
    type = 'path'
    template = ' {{ .Path }} '
    background = '#8700ff'
    foreground = '#eeeeee'
    powerline_symbol = ''
    style = 'powerline'
   
    [blocks.segments.properties]
    folder_icon = ''
    folder_separator_icon = "  "
    home_icon = ""
    style = "agnoster"

  [[blocks.segments]]
    type = 'git'
    style = 'powerline'
    powerline_symbol = ''
    template = '  {{ .HEAD }}{{ if .Staging.Changed }}<#eeeeee>  {{ .Staging.String }}</>{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if gt .StashCount 0 }}  {{ .StashCount }}{{ end }} '
    background = '#875fff'
    foreground = '#eeeeee'

    [blocks.segments.properties]
      branch_icon = ' '
      cherry_pick_icon = ' '
      commit_icon = ' '
      fetch_status = true
      fetch_upstream_icon = true
      merge_icon = ' '
      no_commits_icon = ' '
      rebase_icon = ' '
      revert_icon = ' '
      tag_icon = ' '

[[blocks]]
alignment = "left"
newline = true
type = "prompt"

  [[blocks.segments]]
  foreground = "magenta"
  style = "plain"
  template = " ❯"
  type = "text"

[transient_prompt]
  foreground_templates = [
    "{{if gt .Code 0}}red{{end}}",
    "{{if eq .Code 0}}magenta{{end}}",
  ]
  background = 'transparent'
  template = '❯ '
