# Theme
import = [
   "~/.config/alacritty/alacritty-themes/tokyonight_night.toml"
]

[window]
opacity = 0.7

padding.x = 10
padding.y = 10

decorations = "Full"
decorations_theme_variant = "Dark"

[font]
normal.family = "JetBrainsMono Nerd Font"
bold.family = "JetBrainsMono Nerd Font"
italic.family = "JetBrainsMono Nerd Font"
bold_italic.family = "JetBrainsMono Nerd Font"

size = 12.0
